version: "3.8"

services:
  notiz-app:
    image: ghcr.io/godsizee/notiz-pwa:master
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=${NEXT_PUBLIC_POCKETBASE_URL:-https://pb.dasdann.jetzt}
      - POCKETBASE_URL=${POCKETBASE_URL:-http://pocketbase:8090}
    depends_on:
      - pocketbase
    restart: always

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - "8090:8090"
    environment:
      - PB_SUPERUSER_EMAIL=badesebastian@outlook.com
      - PB_SUPERUSER_PASSWORD=Arschmusik11
    volumes:
      - pb_data:/pb_data
      - pb_public:/pb_public
    restart: always

volumes:
  pb_data:
  pb_public:
